# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='uuid',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
